swarrot:
  connections:
    rabbitmq.streaming:
      url: "amqp://%env(RABBITMQ_CLASSIC_USER)%:%env(RABBITMQ_CLASSIC_PASSWORD)%@%env(RABBITMQ_CLASSIC_HOST)%:%env(RABBITMQ_CLASSIC_PORT)%/streaming"

  messages_types:
    common:
      connection: rabbitmq.streaming
      exchange: ''

  consumers:
    event.process:
      processor: App\Processor\EventProcessor
      middleware_stack:
        - configurator: swarrot.processor.insomniac
        - configurator: swarrot.processor.max_messages
          extras:
            max_messages: 2000
        - configurator: swarrot.processor.ack
          extras:
            requeue_on_error: true

    event.history.process:
      processor: App\Processor\EventHistoryProcessor
      middleware_stack:
        - configurator: swarrot.processor.insomniac
        - configurator: swarrot.processor.max_messages
          extras:
            max_messages: 2000
        - configurator: swarrot.processor.ack
          extras:
            requeue_on_error: true

services:
  App\Processor\EventProcessor:
    arguments:
      - '@App\Provider\SongkickProvider'
      - '@swarrot.publisher'
      - '@soundcharts_wrapper.serializer'

  App\Processor\EventHistoryProcessor:
    arguments:
      - '@App\Provider\SongkickProvider'
      - '@swarrot.publisher'
      - '@soundcharts_wrapper.serializer'
