swarrot:
  connections:
    rabbitmq:
      url: "amqp://%env(RABBITMQ_MAIN_USER)%:%env(RABBITMQ_MAIN_PASSWORD)%@%env(RABBITMQ_MAIN_HOST)%:%env(RABBITMQ_MAIN_PORT)%/%env(RABBITMQ_MAIN_VHOST)%"

  messages_types:
    common:
      connection: rabbitmq
      exchange: ''

  consumers:
    event.process:
      processor: App\Processor\EventProcessor
      middleware_stack:
        - configurator: swarrot.processor.insomniac
        - configurator: swarrot.processor.max_messages
          extras:
            max_messages: 2000
        - configurator: swarrot.processor.ack
          extras:
            requeue_on_error: true

    event.history.process:
      processor: App\Processor\EventHistoryProcessor
      middleware_stack:
        - configurator: swarrot.processor.insomniac
        - configurator: swarrot.processor.max_messages
          extras:
            max_messages: 2000
        - configurator: swarrot.processor.ack
          extras:
            requeue_on_error: true

    venue.process:
      processor: App\Processor\VenueProcessor
      middleware_stack:
        - configurator: swarrot.processor.insomniac
        - configurator: swarrot.processor.max_messages
          extras:
            max_messages: 2000
        - configurator: swarrot.processor.ack
          extras:
            requeue_on_error: true

services:
  App\Processor\EventProcessor:
    arguments:
      - '@App\Provider\SongkickProvider'
      - '@swarrot.publisher'
      - '@soundcharts_wrapper.serializer'

  App\Processor\EventHistoryProcessor:
    arguments:
      - '@App\Provider\SongkickProvider'
      - '@swarrot.publisher'
      - '@soundcharts_wrapper.serializer'

  App\Processor\VenueProcessor:
    arguments:
      - '@songkick.provider'
      - '@swarrot.publisher'
      - '@soundcharts_wrapper.serializer'
