filter:
  path: [src/*]
  excluded_paths:
    - "tests/"
  dependency_paths:
    - "vendor/"
checks:
  php:
    fix_php_opening_tag: false
    remove_php_closing_tag: false
    no_mixed_inline_html: false
    require_braces_around_control_structures: false
    psr2_control_structure_declaration: false
    avoid_superglobals: true
    security_vulnerabilities: true
    no_exit: true
    properties_in_camelcaps: true
    parameters_in_camelcaps: true
    parameter_doc_comments: true
    no_goto: true
    more_specific_types_in_doc_comments: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: false
      order_alphabetically: false
    fix_line_ending: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: true
      verify_parent_constraints: true
tools:
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR2
  external_code_coverage: true
build:
  environment:
    mongodb: false
    redis: false
    mysql: true
    postgresql: false
  dependencies:
    override:
      - composer install -n --ignore-platform-reqs
  tests:
    override: true
